---
name: Setup Environment
description: Setup Environment


runs:
  using: composite
  steps:
    - name: Setup Secrets
      shell: bash
      run: |
        echo ${{ secrets.KEYSTORE_FILE }} | base64 --decode > spacelaunchnow.keystore
        echo ${{ secrets.PUBLISHER_KEY }} | base64 --decode > publisher-key.json
        echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 --decode >keystore.properties
        echo ${{ secrets.GRADLE_PROPERTIES }} | base64 --decode > gradle.properties
        echo ${{ secrets.GOOGLE_SERVICE }} | base64 --decode > mobile/google-services.json
        echo ${{ secrets.API_KEYS }} | base64 --decode > common/src/main/res/values/api_keys.xml
    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin
        cache: gradle
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
    - name: Change wrapper permissions
      shell: bash
      run: chmod +x ./gradlew

