name: Android Build

on:
  push:
    branches-ignore: [master]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Secrets
        shell: bash
        run: |
          echo ${{ secrets.KEYSTORE_FILE }} | base64 --decode > spacelaunchnow.keystore
          echo ${{ secrets.PUBLISHER_KEY }} | base64 --decode > publisher-key.json
          echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 --decode >keystore.properties
          echo ${{ secrets.GRADLE_PROPERTIES }} | base64 --decode > gradle.properties
          echo ${{ secrets.GOOGLE_SERVICE }} | base64 --decode > mobile/google-services.json
          echo ${{ secrets.API_KEYS }} | base64 --decode > common/src/main/res/values/api_keys.xml

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run Test
        uses: ./.github/actions/run-tests

      - name: Build Project
        run: ./gradlew clean assembleDebug