name: Android Build

on:
  push:
    branches:
      - "workflow/initial_testing"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Secrets
        run: |
          echo ${{ secrets.KEYSTORE_FILE }} | base64 --decode > spacelaunchnow.keystore
          echo ${{ secrets.PUBLISHER_KEY }} | base64 --decode > publisher-key.json
          echo ${{ secrets.KEYSTORE_PROPERTIES }} | base64 --decode >keystore.properties
          echo ${{ secrets.GRADLE_PROPERTIES }} | base64 --decode > gradle.properties
          echo ${{ secrets.GOOGLE_SERVICE }} | base64 --decode > mobile/google-services.json
          echo ${{ secrets.API_KEYS }} | base64 --decode > common/src/main/res/values/api_keys.xml

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble